inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'

Metrics/LineLength:
  Enabled: false

#http://viget.com/extend/just-use-double-quoted-ruby-strings
#Style/StringLiterals:
#  EnforcedStyle: double_quotes
